### ISSUE TITLE
please provide some screenshots and/or screencasts

### ISSUE THREAD

**Issue by abuassar** [abublihi/hijri-date-picker#1]
for example this repo contains hijri calendar for android:
https://github.com/alhazmy13/HijriDatePicker

the author provided plenty of screenshots and screencasts to demonstrate the look and behavior of his tool.

please consider adding some to your repo to help us getting an idea about it before installing it.

**Comment by abublihi** [comment]
Thank you for your interest in this repo,

And I will provide screenshots and screencasts very soon.

**Comment by abublihi** [comment]
Thank You @abuassar for your interest, screencasts was added.

**Comment by abuassar** [comment]
nice job thanks
