### ISSUE TITLE
date is limited to 1355 for hijri

### ISSUE THREAD

**Issue by fahot22** [abublihi/hijri-date-picker#21]
Can i increase the limit of date below 1355 hijri date?

**Comment by abublihi** [comment]
No, as of we are using [moment-hijri](https://github.com/xsoh/moment-hijri), which only support dates from 1356 to 1500,

but i will consider this issue as feature request, and I will try to resolve it manualy. 

شكراً لك

**Comment by fahot22** [comment]
Thank You...
