### ISSUE TITLE
Adding onChange onFocus events

### ISSUE THREAD

**Issue by AbdelrahmanAbdelrazek** [abublihi/hijri-date-picker#7]
Hi,

I'd love if I can treat the hijri-date-picker just like any normal `<input>` with `onChange` and `onFocus` events.
Also it would be great if I can make it controlled or uncontrolled, just like [this example](https://codesandbox.io/s/8895j3v2yj) 
so it can be integrated easily with other libraries like [redux-form](https://github.com/erikras/redux-form).

I would be happy to send in a pull request.

Thanks

**Comment by abublihi** [comment]
Thanks for your interest,

Pull requests are welcome 😊
